version: "3.8"

services:
  app:
    build: ./
    ports:
      - 9000:9000
    restart: always
    container_name: auroraiot-backend
    volumes:
      - ~/auroraiot/logs:/app/logs
    network_mode: bridge



