name: Deploy to Oracle Cloud US

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4

      - name: Removing previous container
        run: docker compose down || true

      - name: Add .env file from repository secrets
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Creating and starting new container
        run: docker compose up --build -d || true