name: deploy-to-raspberrypi
on:
  push:
    branches: [master]
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Add .env file from repository secrets
        run: echo "${{ secrets.ENV_FILE }}" > .env
      - name: Build the Docker image
        run: sudo docker build . --file Dockerfile --tag auroraiot
      - name: Run AuroraIOT container 
        run: sudo docker run -d -p 8000:8000 --restart=always --name auroraiot-backend auroraiot
