name: deploy-to-raspberrypi
on:
  push:
    branches: [master]
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: sudo docker build . --file Dockerfile --tag auroraiot:$(date +%s)
      - name: Run AuroraIOT container 
        run: sudo docker run -d -p 8000:8000 auroraiot
